CBV/CBV/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('cmb', views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('',include('basic_app.urls', namespace='basic_app')),
    
]

CBV/basic_app/urls.py
from django.urls import path, re_path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(), name='school_list'),
    # path('(?p<pk>[-\w]+/$)',views.SchoolDetailView.as_view(), name='school_detail'),
    # path('basic_app/(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='school_detail'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='school_detail'),
    re_path('basic_app/create/$', views.SchoolCreateView.as_view(), name='create'),
    path('basic_app/school_update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('basic_app/school_delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete'),
    path('basic_app/school_list',views.SchoolListView.as_view(), name='school_list'),
    # path('basic_app/create/$', views.SchoolCreateView.as_view(), name='create'),
    

]

CBV/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('basic_app:school_detail',kwargs={'pk':self.pk})

    
class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField() 
    school = models.ForeignKey(School,on_delete=models.CASCADE, related_name='students')

    def __str__(self):
        return self.name
    


CBV/basic_app/views.py
# from django.shortcuts import render
from django.views.generic import (TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView)
from . import models
from django.urls import reverse_lazy
# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwarg):
        context = super().get_context_data(**kwarg)
        context['Inject_me'] = 'Bro you are doing it well!!'
        return context

class SchoolListView(ListView):
    context_object_name = 'school_list'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name  = 'basic_app/school_detail.html'    
class SchoolCreateView(CreateView):
    # context_object_name = 'create'
    fields = ('name', 'principal', 'location' )
    model = models.School
    
class SchoolUpdateView(UpdateView):
    model = models.School
    fields = ('name', 'principal', 'location' )

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basic_app:school_list')

CBV/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Project</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'basic_app:school_list' %}">Schools</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin Panel</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    
{% block body_block %}
 
<h3>Hello Everyone Welcome to our project!!</h3>


{% endblock %}
</body>
</html>

CBV/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
  <h1>
    Delete {{school.name}} </h1>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Delete" class="btn btn-danger">
       <a class="btn btn-blue btn-info" href="{% url 'basic_app:school_detail' pk=school.pk %}">Cancel</a>
    </form>
  

    
  </h1>
  
{% endblock %}

CBV/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

<div class="'jumbotron">
    <h1>Welcome to Detail view of School!!</h1>
    <h2>School Detail:</h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Name: {{school_detail.principal}}</p> 
    <p>Name: {{school_detail.location}}</p>
 <h3>Studnets</h3>
{% for Student in school_detail.students.all %}
<p>{{Student.name}} who is {{Student.age}}</p>
{% endfor %}
</div>
<div class="container-fluid">
<p>
    <a class="btn btn-warning" href="{%url 'basic_app:update' pk=school_detail.pk %}">Update</a>
    <a class="btn btn-danger" href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a>
</p>
</div>


{% endblock %}

CBV/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
  <h1>
    {% if not form.instance.pk %}
      Create School </h1>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" class="btn btn-primary">
      </form>
    {% else %}
     <h1> Update School</h1>
     <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" class="btn btn-primary">
      </form>
     
    {% endif %}
    
  
{% endblock %}

CBV/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
  <div class="container">
    <h1>Welcome to a list of all the Schools!!</h1>
    <ul class="list-group">
      {% for school in school_list %}
        <li class="list-group-item">
          <a href="{% url 'basic_app:school_detail' pk=school.id %}" class="text-decoration-none text-dark">{{ school.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

CBV/basic_app/templates/basic_app/school_update.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
  <h1>
    {% if not form.instance.pk %}
      Create School
    {% else %}
      Update School
    {% endif %}
  </h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" class="btn btn-primary">
  </form>
{% endblock %}

CBV/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Project</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'basic_app:school_list' %}">Schools</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin Panel</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    
{% block body_block %}
 
<h3>Hello Everyone Welcome to our project!!</h3>


{% endblock %}
</body>
</html>

CBV/templates/index.html
{% extends 'base.html'   %}
{% block body_block%}

<h4>Index Page</h4>

<p>{{Inject_me}}</p>
{%endblock%}